version: '3'
services:
  api:
    build: .
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://postgres:P4ssw0rd@db/postgres
      - JWT_SECRET=b00fd56-bdb6-4c44-904c-8ee3f76386f3
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P4ssw0rd
      POSTGRES_DB: postgres
    volumes:
      - ./.data:/var/lib/postgresql/data
